
   
	/*-------- africa----------*/
	INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Algeria","dz","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Angola","ao","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Benin","bj","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Botswana","bw","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Burkina","bf","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Burundi","bi","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Cameroon","cm","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Cape Verde","cv","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Central African Republic","cf","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Chad","td","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Comoros","km","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Congo","cg","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Congo, Democratic Republic of","cd","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Djibouti","dj","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Egypt","eg","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Equatorial Guinea","gq","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Eritrea","er","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Ethiopia","et","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Gabon","ga","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Gambia","gm","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Ghana","gh","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Guinea","gn","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Guinea-Bissau","gw","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Ivory Coast","ci","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Kenya","ke","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Lesotho","ls","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Liberia","lr","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Libya","ly","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Madagascar","mg","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Malawi","mw","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Mali","ml","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Mauritania","mr","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Mauritius","mu","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Morocco","ma","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Mozambique","mz","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Namibia","na","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Niger","ne","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Nigeria","ng","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Rwanda","rw","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Sao Tome and Principe","st","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Senegal","sn","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Seychelles","sc","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Sierra Leone","sl","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Somalia","so","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("South Africa","za","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("South Sudan","ss","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Sudan","sd","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Swaziland","sz","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Tanzania","tz","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Togo","tg","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Tunisia","tn","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Uganda","ug","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Zambia","zm","africa"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Zimbabwe
    ","zw","africa"'I',null);
    /*-------- ASIA----------*/
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Afghanistan","af","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Bahrain","bh","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Bangladesh","bd","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Bhutan","bt","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Brunei","bn","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Burma (Myanmar)","mm","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Cambodia","kh","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("China","cn","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("East Timor","etimor","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("India","in","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Indonesia","id","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Iran","ir","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Iraq","iq","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Israel","il","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Japan","jp","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Jordan","jo","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Kazakhstan","kz","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Korea, North","kp","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Korea, South","kr","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Kuwait","kw","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Kyrgyzstan","kg","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Laos","la","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Lebanon","lb","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Malaysia","my","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Maldives","mv","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Mongolia","mn","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Nepal","np","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Oman","om","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Pakistan","pk","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Philippines","ph","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Qatar","qa","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Russian Federation","ru","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Saudi Arabia","sa","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Singapore","sg","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Sri Lanka","lk","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Syria","sy","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Tajikistan","tj","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Thailand","th","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Turkey","tr","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Turkmenistan","tm","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("United Arab Emirates","ae","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Uzbekistan","uz","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Vietnam","vn","asia"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Yemen","ye","asia"'I',null);
    /*-------- EUROPE----------*/
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Albania","al","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Andorra","ad","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Armenia","am","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Austria","at","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Azerbaijan","az","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Belarus","by","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Belgium","be","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Bosnia and Herzegovina","ba","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Bulgaria","bg","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Croatia","hr","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Cyprus","cy","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Czech Republic","cz","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Denmark","dk","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Estonia","ee","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Finland","fi","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("France","fr","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Georgia","ge","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Germany","de","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Greece","gr","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Hungary","hu","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Iceland","is","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Ireland","ie","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Italy","it","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Latvia","lv","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Liechtenstein","li","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Lithuania","lt","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Luxembourg","lu","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Macedonia","mk","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Malta","mt","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Moldova","md","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Monaco","mc","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Montenegro","mj","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Netherlands","nl","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Norway","no","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Poland","pl","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Portugal","pt","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Romania","ro","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("San Marino","sm","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Serbia","mj","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Slovakia","sk","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Slovenia","si","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Spain","es","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Sweden","se","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Switzerland","ch","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Ukraine","ua","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("United Kingdom","uk","europe"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Vatican City","va","europe"'I',null);


    /*-------- north america----------*/
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Antigua and Barbuda","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Bahamas","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Barbados","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Belize","camerica","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Canada","ca","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Costa Rica","camerica","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Cuba","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Dominica","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Dominican Republic","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("El Salvador","camerica","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Grenada","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Guatemala","camerica","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Haiti","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Honduras","camerica","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Jamaica","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Mexico","mx","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Nicaragua","camerica","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Panama","camerica","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Saint Kitts and Nevis","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Saint Lucia","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Saint Vincent and the Grenadines","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Trinidad and Tobago","caribb","north america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("United States","us","north america"'I',null);

   /*-------- oceania----------*/

    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Australia","au","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Fiji","fj","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Kiribati","ki","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Marshall Islands","mh","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Micronesia","fm","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Nauru","nr","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("New Zealand","nz","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Palau","pw","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Papua New Guinea","pg","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Samoa","ws","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Solomon Islands","sb","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Tonga","to","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Tuvalu","tv","oceania"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Vanuatu","vu","oceania"'I',null);
    /*-------- south america----------*/
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Argentina","ar","south america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Bolivia","bo","south america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Brazil","br","south america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Chile","cl","south america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Colombia","co","south america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Ecuador","ec","south america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Guyana","gy","south america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Paraguay","py","south america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Peru","pe","south america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Suriname","sr","south america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Uruguay","uy","south america"'I',null);
    INSERT INTO `tb_country` (`name`,`abv`,`continent`,`status`,`language`) VALUES("Venezuela","ve","south america"'I',null);
