
INSERT INTO `tb_programs` (`id_program`, `name`, `imagePath`, `id_grp_program`, `callFunction`) VALUES
(1, 'Upload Zone', 'upload.png', 1, 'callUploadWindow(this,''upload'')'),
(2, 'Wexplore', 'folder.png', 1, 'callWindowWExplore(this,''wexplore'','''',''normal'','''','''','''')'),
(3, 'WDoc', 'doc.png', 2, 'callWindowWdoc(this,''wdoc'','''','''','''')'),
(4, 'Wnpad', 'txt.png', 2, 'callWindowWnpad(this,''wnpad'','''',''normal'','''')'),
(5, 'GDocs', 'gdocs.png', 3, 'callWindowGdocs(this,''gdocs'','''','''')'),
(6, 'Pdf Viewer', 'pdf-viewer.png', 3, 'callWindowPdf_viewer(this,''php_viewer'','''','''')'),
(7, 'Sound Manager', 'sound.png', 4, 'callWindowSoundManager(this,''soundmanager'','''','''','''')'),
(8, 'WAudio', 'waudio.png', 4, 'callWindowWaudio(this,''waudio'','''','''')'),
(9, 'WVideo', 'video_logo.png', 4, 'callWindowWvideo(this,''wvideo'',''setMediaElement(\\''wvideo\\'')'),
(10, 'Ytb Manager', 'ytd.png', 4, 'callWindowYtbManager(this,''ytbmanager'','''','''','''')'),
(11, 'Galleria', 'galleria.png', 5, 'callWindowGalleria(this,''galleria'','''','''','''')'),
(12, 'Imanager', 'imanager.png', 5, 'callWindowImanager(this,''imanager'','''','''','''')'),
(13, 'Wcarousel', 'wcarousel.png', 5, 'callWindowWCarousel(this,''wcarousel'','''','''','''')'),
(14, 'WSlider', 'wslider.png', 5, 'callWindowWSlider(this,''wslider'','''','''','''')'),
(15, 'Xml Editor', 'xml.png', 6, 'callWindowXmlEditor(this,''xmleditor'','''','''','''')'),
(16, 'Html Editor', 'html.png', 6, 'callWindowHtmlEditor(this,''htmleditor'','''','''','''')'),
(17, 'Php Editor', 'php.png', 6, 'callWindowPhpEditor(this,''phpeditor'','''','''','''')'),
(18, 'Ccharp Editor', 'cs.png', 6, 'callWindowCcharpEditor(this,''ccharpeditor'','''','''','''')'),
(19, 'Css Editor', 'css.png', 6, 'callWindowCssEditor(this,''csseditor'','''','''','''')'),
(20, 'Django Editor', 'django.png', 6, 'callWindowDjangoEditor(this,''djangoeditor'','''','''','''')'),
(21, 'Java Editor', 'java.png', 6, 'callWindowJavaEditor(this,''javaeditor'','''','''','''')'),
(22, 'JsEditor', 'js.png', 6, 'callWindowJsEditor(this,''jseditor'','''','''','''')'),
(23, 'Python Editor', 'python.png', 6, 'callWindowPythonEditor(this,''pythoneditor'','''','''','''')'),
(24, 'Sql Editor', 'sql.png', 6, 'callWindowSqlEditor(this,''sqleditor'','''','''','''')');